### ISSUE TITLE
Save the message and resend later

### ISSUE THREAD

**Issue by Edward-Zhou** [wechaty/dotnet-wechaty#10]
I have a requirement like, 

I want to save the message from specific user, and resend it to other users later, maybe repeat.

I checked existing issue and found something related like wechaty/wechaty#1857 and wechaty/wechaty#2073.

For wechaty/wechaty#1857 , I am wondering if I saved the messageId, delete the message from wechat, will it be able to load the message?

In addition, I did not see "bot.Message.load" on **Wechaty.Grpc** C# NUGET Version.

I am able to find the similiar method in [dotnet-wechaty](https://github.com/wechaty/dotnet-wechaty).

Which is the recommended way to use under C#, **Wechaty.Grpc** C# NUGET Version or [dotnet-wechaty](https://github.com/wechaty/dotnet-wechaty)?

One more short issue may not be posted here, has [dotnet-wechaty](https://github.com/wechaty/dotnet-wechaty) been published to nuget? I did not find the nuget version.

**Comment by huan** [comment]
Transfer this issue to dotnet-wechaty because it's .Net related. @wechaty/dotnet

**Comment by Jesn** [comment]
@Edward-Zhou   目前已经出了一个基础版的dotnet-wechaty-getting-started 可以使用   https://github.com/wechaty/dotnet-wechaty-getting-started
