### ISSUE TITLE
Support WECHATY_PUPPET_SERVICE_TOKEN

### ISSUE THREAD

**Issue by huan** [wechaty/dotnet-wechaty#26]
1. Add `WECHATY_PUPPET_SERVICE_TOKEN` support for all our Polyglot Wechaty projects.
2. Make `WECHATY_PUPPET_HOSTIE_TOKEN` an alias for `WECHATY_PUPPET_SERVICE_TOKEN`, and print a warning message to let the user know it was deprecated with it has been set.

Learn more from https://github.com/wechaty/wechaty/issues/2123

**Comment by Jesn** [comment]
ok， will be revised tomorrow

**Comment by Jesn** [comment]
- [x] rename Wechaty.Module.PuppetHostie -> Wechaty.Module.PuppetService
- [x] rename WECHATY_PUPPET_HOSTIE_TOKEN ->WECHATY_PUPPET_SERVICE_TOKEN

**Comment by huan** [comment]
It's great to know that you can revise it tomorrow, thank you very much!

**Comment by huan** [comment]
@Jesn Can we link the related links / or to this issue?

We should always link code changes to the related issue so that everything will be clearer for all developers.

**Comment by Jesn** [comment]
pull request  https://github.com/wechaty/dotnet-wechaty/pull/27

**Comment by huan** [comment]
@Jesn Thank you very much for linking this Issue to the implementing PR!
