### ISSUE TITLE
add room member failed, error code: -2001, error message: 由于系统升级，该功能无法使用，请升级版本

### ISSUE THREAD

**Issue by softpeng** [wechaty/dotnet-wechaty#40]
执行加入群组操作报错：
`await roomTobeAdd.Add(contact);`

报错信息如下：
Grpc.Core.RpcException:“Status(StatusCode="Internal", Detail="ERR_ADD_ROOM add room member failed, error code: -2001, error message: 由于系统升级，该功能无法使用，请升级版本.")”

**Comment by softpeng** [comment]
确切来说这里应该是企业微信的问题，外部成员加入加入内部群报错。建议优化报错信息，issue先关闭。

**Comment by Jesn** [comment]
这个提示是Grpc反馈过来的提示，可以根据  code: -2001 业务里面做下处理
