### ISSUE TITLE
Room class has errors when rebuild the code

### ISSUE THREAD

**Issue by kevincheng201903** [wechaty/dotnet-wechaty#5]
![image](https://user-images.githubusercontent.com/7588533/97784146-5ef58780-1bd7-11eb-8655-91fd3ee5c5a4.png)

**Comment by kevincheng201903** [comment]
**room = new Room(id, WechatyInstance, Puppet, _loggerForRoom, _name);**


        /// <summary>
        /// init <see cref="Room"/>
        /// </summary>
        /// <param name="id"></param>
        /// <param name="wechaty"></param>
        /// <param name="logger"></param>
        /// <param name="name"></param>
        public Room([DisallowNull] string id,
                    [DisallowNull] Wechaty wechaty,
                    [DisallowNull] ILogger<Room> logger,
                    [AllowNull] string? name = null) : base(wechaty, logger, name)
        {
            Id = id;
            if (Logger.IsEnabled(LogLevel.Trace))
            {
                Logger.LogTrace($"constructor({Id})");
            }
        }

**Comment by kevincheng201903** [comment]
there are only four arguments in the Room constructor class,but you init the Room class with five arguments in RoomRepository class

**Comment by GuoqiuZhong** [comment]
I‘ve tried , the same error. I think it should be change like below.
![image](https://user-images.githubusercontent.com/23632542/97800591-679a9c00-1c71-11eb-8165-f9d9ac496875.png)

**Comment by echofool** [comment]
temporarily resolved at #9

**Comment by Jesn** [comment]
@kevincheng201903  wechaty 已更新，而且已出了一个基础版的dotnet-wechaty-getting-started 可以使用 https://github.com/wechaty/dotnet-wechaty-getting-started
