### ISSUE TITLE
Wechaty class error

### ISSUE THREAD

**Issue by kevincheng201903** [wechaty/dotnet-wechaty#6]
public async Task Start()     

    --->   OnHeartbeat(() => MemoryCheck());

There is no MemoryCheck function in your C# code

**Comment by GuoqiuZhong** [comment]
I‘m looking forward to this fixing.

**Comment by echofool** [comment]
temporarily resolved at https://github.com/wechaty/dotnet-wechaty/pull/9

**Comment by Jesn** [comment]
Updated
