### ISSUE TITLE
Puppet is abstract class, can't construct it.

### ISSUE THREAD

**Issue by GuoqiuZhong** [wechaty/dotnet-wechaty#7]
The wechaty constructor needs the options containing Puppet instance, but Puppet is defined as abstract. So I can't create an instance of it and pass it to WechatyOptions.
![image](https://user-images.githubusercontent.com/23632542/97801392-50f74380-1c77-11eb-83b2-17f3e5277514.png)
![image](https://user-images.githubusercontent.com/23632542/97801405-71bf9900-1c77-11eb-8c1e-5f7811fe402d.png)

**Comment by Edward-Zhou** [comment]
got the same issue.

**Comment by Jesn** [comment]
@GuoqiuZhong 目前已经出了一个基础版的dotnet-wechaty-getting-started 可以使用 https://github.com/wechaty/dotnet-wechaty-getting-started
