### ISSUE TITLE
Can't send Message after logging in a while.

### ISSUE THREAD

**Issue by GuoqiuZhong** [wechaty/dotnet-wechaty#8]
I tried to send a file, it threw an exception as below.  
![image](https://user-images.githubusercontent.com/23632542/97801705-88ff8600-1c79-11eb-9932-21f03e25b737.png)

And the console doesn't show information any more , no mention hearbeat.
![image](https://user-images.githubusercontent.com/23632542/97801784-28bd1400-1c7a-11eb-8395-298674ebd13e.png)

**Comment by Jesn** [comment]
@GuoqiuZhong  abp版本的已经合并到 `dotnet-wechat`，不在维护abp.wechaty 了
